package com.cloud.basicfun.daos;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.cloud.basicfun.beans.AppendPositionBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "appendPosition".
*/
public class AppendPositionBeanDao extends AbstractDao<AppendPositionBean, Long> {

    public static final String TABLENAME = "appendPosition";

    /**
     * Properties of entity AppendPositionBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "id");
        public final static Property Position = new Property(1, long.class, "position", false, "position");
        public final static Property OriginalFileName = new Property(2, String.class, "originalFileName", false, "originalFileName");
        public final static Property FileName = new Property(3, String.class, "fileName", false, "fileName");
        public final static Property FilePath = new Property(4, String.class, "filePath", false, "filePath");
    }


    public AppendPositionBeanDao(DaoConfig config) {
        super(config);
    }
    
    public AppendPositionBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"appendPosition\" (" + //
                "\"id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"position\" INTEGER NOT NULL ," + // 1: position
                "\"originalFileName\" TEXT," + // 2: originalFileName
                "\"fileName\" TEXT," + // 3: fileName
                "\"filePath\" TEXT);"); // 4: filePath
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_appendPosition_id ON \"appendPosition\"" +
                " (\"id\" ASC);");
        db.execSQL("CREATE INDEX " + constraint + "IDX_appendPosition_originalFileName ON \"appendPosition\"" +
                " (\"originalFileName\" ASC);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"appendPosition\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, AppendPositionBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getPosition());
 
        String originalFileName = entity.getOriginalFileName();
        if (originalFileName != null) {
            stmt.bindString(3, originalFileName);
        }
 
        String fileName = entity.getFileName();
        if (fileName != null) {
            stmt.bindString(4, fileName);
        }
 
        String filePath = entity.getFilePath();
        if (filePath != null) {
            stmt.bindString(5, filePath);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, AppendPositionBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getPosition());
 
        String originalFileName = entity.getOriginalFileName();
        if (originalFileName != null) {
            stmt.bindString(3, originalFileName);
        }
 
        String fileName = entity.getFileName();
        if (fileName != null) {
            stmt.bindString(4, fileName);
        }
 
        String filePath = entity.getFilePath();
        if (filePath != null) {
            stmt.bindString(5, filePath);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public AppendPositionBean readEntity(Cursor cursor, int offset) {
        AppendPositionBean entity = new AppendPositionBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // position
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // originalFileName
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // fileName
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // filePath
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, AppendPositionBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPosition(cursor.getLong(offset + 1));
        entity.setOriginalFileName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setFileName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setFilePath(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(AppendPositionBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(AppendPositionBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(AppendPositionBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
