package com.cloud.basicfun.daos;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.cloud.basicfun.beans.BreakPointBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "breakPoint".
*/
public class BreakPointBeanDao extends AbstractDao<BreakPointBean, Long> {

    public static final String TABLENAME = "breakPoint";

    /**
     * Properties of entity BreakPointBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "id");
        public final static Property OriginalFileName = new Property(1, String.class, "originalFileName", false, "originalFileName");
        public final static Property FileName = new Property(2, String.class, "fileName", false, "fileName");
        public final static Property FilePath = new Property(3, String.class, "filePath", false, "filePath");
        public final static Property RecordDirectory = new Property(4, String.class, "recordDirectory", false, "recordDirectory");
    }


    public BreakPointBeanDao(DaoConfig config) {
        super(config);
    }
    
    public BreakPointBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"breakPoint\" (" + //
                "\"id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"originalFileName\" TEXT," + // 1: originalFileName
                "\"fileName\" TEXT," + // 2: fileName
                "\"filePath\" TEXT," + // 3: filePath
                "\"recordDirectory\" TEXT);"); // 4: recordDirectory
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_breakPoint_id ON \"breakPoint\"" +
                " (\"id\" ASC);");
        db.execSQL("CREATE INDEX " + constraint + "IDX_breakPoint_originalFileName ON \"breakPoint\"" +
                " (\"originalFileName\" ASC);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"breakPoint\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, BreakPointBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String originalFileName = entity.getOriginalFileName();
        if (originalFileName != null) {
            stmt.bindString(2, originalFileName);
        }
 
        String fileName = entity.getFileName();
        if (fileName != null) {
            stmt.bindString(3, fileName);
        }
 
        String filePath = entity.getFilePath();
        if (filePath != null) {
            stmt.bindString(4, filePath);
        }
 
        String recordDirectory = entity.getRecordDirectory();
        if (recordDirectory != null) {
            stmt.bindString(5, recordDirectory);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, BreakPointBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String originalFileName = entity.getOriginalFileName();
        if (originalFileName != null) {
            stmt.bindString(2, originalFileName);
        }
 
        String fileName = entity.getFileName();
        if (fileName != null) {
            stmt.bindString(3, fileName);
        }
 
        String filePath = entity.getFilePath();
        if (filePath != null) {
            stmt.bindString(4, filePath);
        }
 
        String recordDirectory = entity.getRecordDirectory();
        if (recordDirectory != null) {
            stmt.bindString(5, recordDirectory);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public BreakPointBean readEntity(Cursor cursor, int offset) {
        BreakPointBean entity = new BreakPointBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // originalFileName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // fileName
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // filePath
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // recordDirectory
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, BreakPointBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setOriginalFileName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setFileName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setFilePath(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setRecordDirectory(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(BreakPointBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(BreakPointBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(BreakPointBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
